services:
  database:
    image: mysql:latest
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - backend:/var/lib/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    restart: on-failure
    ports:
      - 4200:4200
    volumes:
      - frontend:/var/lib/frontend

volumes:
  database:
    driver: local
  backend:
    driver: local
  frontend:
    driver: local
