// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/desenvolvedores": {
            "get": {
                "description": "Retorna todos os desenvolvedores cadastrados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desenvolvedores"
                ],
                "summary": "Listar desenvolvedores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Campo para ordenação (ex: nome)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Direção da ordenação (ASC ou DESC)",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Texto de busca",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de desenvolvedores",
                        "schema": {
                            "$ref": "#/definitions/presenter.DesenvolvedorPaginatedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo desenvolvedor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desenvolvedores"
                ],
                "summary": "Criar desenvolvedor",
                "parameters": [
                    {
                        "description": "Dados do desenvolvedor",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Desenvolvedor"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presenter.Desenvolvedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/desenvolvedores/{id}": {
            "put": {
                "description": "Atualiza um desenvolvedor existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desenvolvedores"
                ],
                "summary": "Atualizar desenvolvedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do desenvolvedor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do desenvolvedor",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Desenvolvedor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.Desenvolvedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um desenvolvedor pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desenvolvedores"
                ],
                "summary": "Remover desenvolvedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do desenvolvedor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Removido com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/niveis": {
            "get": {
                "description": "Retorna todos os níveis cadastrados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Níveis"
                ],
                "summary": "Listar níveis",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Campo para ordenação (ex: nome)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Direção da ordenação (ASC ou DESC)",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Texto de busca",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de níveis",
                        "schema": {
                            "$ref": "#/definitions/presenter.NivelPaginatedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo nível",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Níveis"
                ],
                "summary": "Criar nível",
                "parameters": [
                    {
                        "description": "Dados do nível",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Nivel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presenter.Nivel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/niveis/select-options": {
            "get": {
                "description": "Retorna opções simplificadas de níveis para uso em selects",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Níveis"
                ],
                "summary": "Listar opções de níveis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presenter.NivelSelectOptions"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/niveis/{id}": {
            "put": {
                "description": "Atualiza um nível existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Níveis"
                ],
                "summary": "Atualizar nível",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do nível",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do nível",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.Nivel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.Nivel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um nível pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Níveis"
                ],
                "summary": "Remover nível",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do nível",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Removido com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Desenvolvedor": {
            "type": "object",
            "properties": {
                "data_nascimento": {
                    "description": "Data de nascimento do desenvolvedor (DD/MM/YYYY)",
                    "type": "string"
                },
                "hobby": {
                    "description": "Hobby do desenvolvedor (Max:100)",
                    "type": "string"
                },
                "id": {
                    "description": "ID do desenvolvedor (UUID)",
                    "type": "string"
                },
                "nivel_id": {
                    "description": "ID do nível (UUID)",
                    "type": "string"
                },
                "nome": {
                    "description": "Nome do desenvolvedor (Max:100)",
                    "type": "string"
                },
                "sexo": {
                    "description": "Sexo do desenvolvedor (M, F)",
                    "type": "string"
                }
            }
        },
        "entity.Nivel": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID do nível (UUID)",
                    "type": "string"
                },
                "nivel": {
                    "description": "Nível do desenvolvedor (Max:100)",
                    "type": "string"
                }
            }
        },
        "presenter.Desenvolvedor": {
            "type": "object",
            "properties": {
                "data_nascimento": {
                    "type": "string"
                },
                "hobby": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nivel": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "nivel": {
                            "type": "string"
                        }
                    }
                },
                "nome": {
                    "type": "string"
                },
                "sexo": {
                    "type": "string"
                }
            }
        },
        "presenter.DesenvolvedorPaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenter.Desenvolvedor"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/presenter.Meta"
                }
            }
        },
        "presenter.Meta": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "last_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "presenter.Nivel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nivel": {
                    "type": "string"
                },
                "qtd_devs": {
                    "type": "string"
                }
            }
        },
        "presenter.NivelPaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenter.Nivel"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/presenter.Meta"
                }
            }
        },
        "presenter.NivelSelectOptions": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nivel": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API Desafio Fullstack Gazin",
	Description:      "API desenvolvida para o desafio fullstack Gazin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
